# Generated by Django 5.0.7 on 2024-07-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accessory",
            options={"verbose_name": "Accessory", "verbose_name_plural": "Accessories"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
    ]
